version: 2
updates:
  # CLI - Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "cli"
      - "deps"
    commit-message:
      prefix: "build"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "ci"
      - "deps"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 3
